<<<<<<< Updated upstream
# Generated by Django 4.2.6 on 2023-11-07 15:35
=======
# Generated by Django 4.1.1 on 2023-11-06 01:52
>>>>>>> Stashed changes

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Description')),
                ('requirements', ckeditor.fields.RichTextField(verbose_name='Requirements')),
                ('attachments', models.FileField(blank=True, null=True, upload_to='job_attachments/', verbose_name='Attachments')),
                ('image', models.ImageField(blank=True, null=True, upload_to='job_images/', verbose_name='Image')),
                ('publish_status', models.CharField(choices=[('Draft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=10, verbose_name='Publish Status')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Deadline')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Created At')),
            ],
        ),
        migrations.CreateModel(
            name='UserApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Applied At')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Review', 'Review'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=10, verbose_name='Status')),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekrutamentu.jobpost', verbose_name='Job Post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Aplicant')),
            ],
        ),
        migrations.CreateModel(
            name='UserAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_file', models.FileField(upload_to='Upload/', verbose_name='Upload dokumentu  ')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rekrutamentu.userapplication', verbose_name='Application')),
            ],
        ),
    ]
